### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by pattyland** [YOURLS/yourls-idn#1]
Do I still need this plugin? My IDN Domain is working fine out of the box!

**Comment by ozh** [comment]
Dunno. Made this by request but I don't have a need for it. You tell us :)

**Comment by pattyland** [comment]
Ok, so what exactly is this plugin doing? I'm seeing JS replacements, is this client/display only?

**Comment by ozh** [comment]
If I remember, it's purely display. Makes sure you end up with "héhé.com/123" instead of "xn--hh-bjab.com/123". Everything should work out of the box, except that without the plugin, those ugly IDN URL are decoded into their uglier decoded form.

**Comment by pattyland** [comment]
I get it. Thanks for the clarification, the plugin is working great! I bought the domain with umlauts only to redirect to the domain without them ;)
